version: '3.0'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: my-secret-pw
      MYSQL_DATABASE: my-database
      MYSQL_USER: my-user
      MYSQL_PASSWORD: my-password
    ports:
      - "3306:3306"
    volumes:
      - ./db-data:/var/lib/mysql